name: Your New Jekyll Site

markdown: kramdown

kramdown:
  use_coderay: true
  coderay:
    coderay_wrap: div
    coderay_line_numbers: nil
    coderay_tab_width: 2
    coderay_css: class

relative_permalinks: false
permalink: articles/:year-:month-:day-:title.html

baseurl: 
